
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_fin_project' 
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'my_fin_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  my_fin_project:
    base_transaction.csv:
      materialized: table

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
 my_fin_project:
   staging:
     +schema: staging
     +materialized: view
   intermediate:
     +schema: intermediate
     +materialized: table
   marts:
     +schema: marts
     +materialized: table
   ingest_excel_data:
     +table_name: 'test'

vars:
  credit_rules:
    rule_1:
      category: Investment
      keywords: ["SO TIET KIEM","KDV","VNDIRECT", "VEOFN003",VIB FN003", "VIBFN003" , "TIEN GUI", "STK", "VEOF", "VEFO", "VIBF", "NTTK", "SJC", "000131823", "SO TICH LUY", " CO KY HAN"]
    rule_2:
      category: Cashout
      keywords: ["RUT TIEN", "RUT TIEN"]
    rule_3:
      category: Online_shopping
      keywords: ["SHOPEEPAY", "MOMO CASHIN"]
    rule_4:
      category: Pet
      keywords: ["THUC AN"]
    rule_5:
      category: Electric_bill
      keywords: ["PE02000051037"]
    rule_6:
      category: Water_bill
      keywords: ["TIEN NUOC", "PHUWACO"]
    rule_7:
      category: Phone_bill
      keywords: ["TIEN DIEN THOAI"]
    rule_8:
      category: Internet_bill
      keywords: ["T008_GFTTH"]
    rule_9:
      category: Foods_n_drinks
      keywords: ["THANH TOAN HANG HOA DICH VU"]
    rule_10:
      category: Healthcare
      keywords: ["Y TE", "KHAM CHUA BENH"]
    rule_11:
      category: Finance_cost
      keywords: ["THANH TOAN THE TIN DUNG", "THU PHI DINH KY TKTM"]
    rule_12:
      category: Education
      keywords: ["COURSERA", "TIEN HOC PHI"]
    rule_13:
      category: House_improvement
      keywords: ["LE VAN DUNG", "BUI THI TUOI", "CAO THI THU THUY", "CMND 083196009809"]
    rule_14:
      category: Wedding_spending
      keywords: ["WEDDING", "DAM CUOI"]
    rule_15:
      category: Lending
      keywords: ["ANH VU", 'HOAI THUONG']
  debit_rules:
    rule_1:
      category: Salary
      keywords: ["LUONG", "LE XUAN MAI", "SALARY"]
    rule_2:
      category: Partner_support
      keywords: ["YEU EM","ANH DANG PREPARE", "TIEN GUI TIET KIEM CUA ANH YEU","ANH YEU","MUA DO HOI NHIEU CHO XIN 500K", "HIY PHUNG", "VO YEU", "YEU VO LAM,TRUA CO AN GI KO A","GUI EM","CON AI YEU EM BANG ANH", "TIEN TIET KIEM", "TIEN TIET KIEM ANH KUTO", "ANH CHONG CU TO", "HUY NGU NGOK", "TIEN NE KHO QUA. CHONG", "TIEN THUONG", "TIEN MUNG TUOI CHO VO", "DEM QUA ANH VUI LAM", "PHUNG NGUYEN QUOC HUY", "TIET KIEM HUY", "HUY PHUNG", "ANH HUY", "DOTA", "ANH EM NUONG TUA"]
    rule_3:
      category: Investment
      keywords: ["SO TIET KIEM","STK", "VEFO", "VIBF", "NTTK 0001213823", "SJC", "000131823", "RUT VON", "TAT TOAN", "VNDIRECT", "KDV", "VINACAPITAL", "VEOF", "NTTK"] 
    rule_4:
      category: Borrow
      keywords: ["BUI THI TUOI", "LE VAN DUNG"]
    rule_5:
      category: Refund
      keywords: ["HOAN", "THUE", "THANH TOAN HANG HOA DICH VU", "MOMO CASHOUT", "CHUYEN TIEN DEN LE XUAN MAI"]
    rule_6:
      category: Investment_interest
      keywords: ["LAI TIEN GUI"]
    rule_7:
      category: Cashing_in
      keywords: ["LE XUAN MAI NOP"] 
  investment_rules:
    rule_1:
      category: Bank_book
      keywords: ["SO TIET KIEM","TIEN GUI", "SO TICH LUY", "STK", "RUT VON", "TAT TOAN", "CO KY HAN"]
    rule_2:
      category: Funding
      keywords: ["VEFO", "VIBF", "VINACAPITAL", "VEOF", "VEOFN003", "VIBFN003", "VIB FN003"]
    rule_3:
      category: Stock
      keywords: ["NTTK 0001213823", "000131823", "NTTK"]
    rule_4:
      category: Gold
      keywords: ["SJC", "KDV"]
    